### ISSUE TITLE
imgadm import failing with OCI images

### ISSUE THREAD

**Issue by gaige** [TritonDataCenter/node-docker-registry-client#39]
Trying to pull some images from dockerhub is failing due to:

```
{
  "name": "imgadm",
  "req_id": "9f8ae8c3-be72-49c7-bef3-3f517bf97572",
  "hostname": "XXXX",
  "pid": 10013,
  "component": "source",
  "source": {
    "type": "docker"
  },
  "level": 10,
  "body": "{\"errors\":[{\"code\":\"MANIFEST_UNKNOWN\",\"message\":\"OCI index found, but accept header does not support OCI indexes\"}]}\n",
  "len": 117,
  "msg": "body received",
  "time": "2023-05-28T10:34:36.458Z",
  "src": {
    "file": "/usr/img/node_modules/docker-registry-client/lib/docker-json-client.js",
    "line": 96,
    "func": "finish"
  },
  "v": 0
}
```

Other images work fine.

Examples of failing images are:

* nginxproxy/nginx-proxy:latest
* yuzutech/kroki:0.21.3

**Comment by bahamat** [comment]
Is this happening with Triton? Or are you trying to use this library separately?

**Comment by gaige** [comment]
It’s happening when importing with `imgadm` in SmartOS. I’m not using the library directly, just through the SmartOS command.

**Comment by bahamat** [comment]
What image/registry is this happening with?

**Comment by gaige** [comment]
@bahamat Here are two examples that I ran into:
- `nginxproxy/nginx-proxy:latest`
- `yuzutech/kroki:0.21.3`

(Any of the tags will do for those images). I haven't been able to isolate a good predictive function on which images won't work, but the `yuzutech/kroki` image worked last year. 

A similar [issue for GitLab](https://gitlab.com/gitlab-org/gitlab-foss/-/merge_requests/31127) indicated that fixing it required adding `application/vnd.oci.image.manifest.v1+json` to the `Accept` header, but that the JSON response was the same format as the standard Docker Distribution V2 manifest.

**Comment by bahamat** [comment]
See [TRITON-2403](https://smartos.org/bugview/TRITON-2403).

**Comment by bahamat** [comment]
As far as *this* repo goes, #40 add support for OCI image mime types. Continue following [TRITON-2403](https://smartos.org/bugview/TRITON-2403) for additional work in sdc-imgapi, sdc-docker, and smartos-live.

[TRITON-2403]: https://mnx.atlassian.net/browse/TRITON-2403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
